### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [scottmangiapane/android-calculator#1]
I took the freedom to add your app [to my repository](https://apt.izzysoft.de/fdroid/index/apk/com.scottmangiapane.calculatorv2), to make installation and update easier for your users (new versions will be automatically retrieved from your tags once you add them – so they get update information via their F-Droid client). As I think your app would be eligible for inclusion with the official [F-Droid](https://f-droid.org/) repo: please let me know if you would like to see it listed there – and I gladly help you with that.

**Comment by scottmangiapane** [comment]
Thank you @IzzySoft! Sorry for the terrible response time, I missed the notification.

I appreciate you adding my app to your repository. Since I'm not doing any more feature work for it though and it never had a ton of users, I don't think it needs to be in the official F-Droid repo... But you are free to add it if that's something you would enjoy doing.

**Comment by IzzySoft** [comment]
Thanks for answering at all, Scott! I'm not using your app myself, but going by the list of thumbs, there seems to be a certain userbase: 6 thumbs-up for such an issue is quite something! But if you plan no future updates, I'm not sure if running through the process at F-Droid.org is needed. If anyone opens an RFP there, I of course will help processing it. And if you want to declare your app "unmaintained" one day, just ping me and I'll update the description at my end as well.

As for missed notifications: Yeah, that happens from time to time, I had that as well…

**Comment by scottmangiapane** [comment]
No problem. And I'm surprised by the thumbs as well! IIRC google analytics only showed 50 active users back when it was on the Play Store, and not many users read the GitHub issues. But I guess it's popular with other developers. And yeah I think adding the "unmaintained" status is a good idea, since I've mostly switched to Node.js development and haven't made an Android app in quite a while. I'll add a note explaining that in the README tomorrow.

**Comment by IzzySoft** [comment]
Ah, scrap analytics :rofl: That's completely overrated. On my devices, GA is blocked (I use LineageOS with microG, so the latter replaces that "Google Crap" by dummies: analytics data is sent to `/dev/null`, ads are never available, map tiles come from OSM, etc). With only 50 users altogether, those 6 thumbs are even more amazing.

I've added a note that your app is no longer *actively* maintained, should show up with the next sync in about 6 hours. Thanks for setting up explanations here as well!

**Comment by scottmangiapane** [comment]
Nice! I'm a fan of LineageOS as well. It's so nice being able to remove all the unwanted bloat from a normal Android setup and just keep the stuff I actually want.

Anyways, thanks again for the support and maintaining the repository metadata. I'll go ahead and close this issue since there's nothing else to do 🙂
